version: '3.8'
services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot
    env_file:
      - ./.env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:4.4
    volumes:
      - mongo-db:/data/db
    restart: unless-stopped

  vue-app:
    build:
      context: ../ryoku-web
      dockerfile: Dockerfile
    container_name: vue_app
    ports:
      - "8080:80"
    volumes:
      - ../ryoku-web/dist:/usr/share/nginx/html
    restart: unless-stopped

volumes:
  mongo-db:
