version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot
    env_file:
      - ./.env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:4.4
    volumes:
      - mongo-db:/data/db
    restart: unless-stopped

  vue_app:
    build:
      context: ../ryoku-web
      dockerfile: Dockerfile
    container_name: vue_app
    ports:
      - "443:8080"
    volumes:
      - ../ryoku-web:/app
      - ./ssl:/app/ssl
    restart: unless-stopped
    command: ["npm" ,"run" ,"serve"]

volumes:
  mongo-db:

